### ISSUE TITLE
Credentials can be set with secrets ?

### ISSUE THREAD

**Issue by lazinessdevs** [AminFazlMondo/deployable-awscdk-app-ts#141]
Hi Amin,

Is there any way to get the `region`, `access key id` and `secret access key` by secret?
Set like this
```ts
workflowNodeVersion: '14.18.1',
deployOptions: {
  environments: [
    {
      name: 'dev',
      awsCredentials: {
        region: '${{ secrets.AWS_REGION }}',
        accessKeyIdSecretName: '${{ secrets.AWS_ACCESS_KEY_ID }}',
        secretAccessKeySecretName: '${{ secrets.AWS_SECRET_ACCESS_KEY }}',
      },
    },
  ]
},
```

**Comment by AminFazlMondo** [comment]
Hi @lazinessdevs ,

These variables are the name of the GitHub Secrets that contain the value for these credentials. Just to be clear on what you are asking, do you wan the secret name to also be a secret?

Cheers,
